/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Gestion_Des_Clients (void)
{
  GtkWidget *Gestion_Des_Clients;
  GtkWidget *eventbox4;
  GtkWidget *alignment22;
  GtkWidget *eventbox3;
  GtkWidget *notebookclient;
  GtkWidget *alignment5;
  GtkWidget *eventbox1;
  GtkWidget *alignment8;
  GtkWidget *eventbox2;
  GtkWidget *fixed1;
  GtkWidget *entryNom;
  GtkWidget *entryPrenom;
  GtkWidget *entryTel;
  GtkWidget *entryMail;
  GtkWidget *entryAdresse;
  GtkWidget *eventbox27;
  GtkWidget *comboboxentryMois;
  GtkWidget *labelCin;
  GtkWidget *labelPrenom;
  GtkWidget *labelTel;
  GtkWidget *labelMail;
  GtkWidget *labelAdresse;
  GtkWidget *label16;
  GtkWidget *labelSex;
  GtkWidget *labelVerifJour;
  GtkWidget *alignment26;
  GtkWidget *eventbox30;
  GtkWidget *comboboxentryJour;
  GtkWidget *buttonVAjout;
  GtkWidget *alignment2;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label13;
  GtkWidget *buttonRAjout;
  GtkWidget *alignment3;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label14;
  GtkWidget *eventbox33;
  GtkWidget *Homme;
  GSList *Homme_group = NULL;
  GtkWidget *eventbox34;
  GtkWidget *Femme;
  GtkWidget *calendarAjout;
  GtkWidget *labelNom;
  GtkWidget *alignment29;
  GtkWidget *entryCin;
  GtkWidget *TbuttonInitAjout;
  GtkWidget *alignment27;
  GtkWidget *hbox17;
  GtkWidget *image25;
  GtkWidget *label76;
  GtkWidget *comboboxentryAnne;
  GtkWidget *label80;
  GtkWidget *Tlabelcheckcalendar;
  GtkWidget *label77;
  GtkWidget *labelVerifAdresse;
  GtkWidget *labelVerifMail;
  GtkWidget *labelVerifTel;
  GtkWidget *labelVerifCin;
  GtkWidget *labelVerifPrenom;
  GtkWidget *labelVerifNom;
  GtkWidget *labelAjoutSucc;
  GtkWidget *label28;
  GtkWidget *image30;
  GtkWidget *labelAjout;
  GtkWidget *fixed3;
  GtkWidget *entryCinModif;
  GtkWidget *labelCinCherch;
  GtkWidget *entryNom2;
  GtkWidget *entryPrenom2;
  GtkWidget *entryCin2;
  GtkWidget *entryTel2;
  GtkWidget *entryMail2;
  GtkWidget *entryAdresse2;
  GtkWidget *label60;
  GtkWidget *label59;
  GtkWidget *label65;
  GtkWidget *label64;
  GtkWidget *label57;
  GtkWidget *label56;
  GtkWidget *label55;
  GtkWidget *label54;
  GtkWidget *eventbox29;
  GtkWidget *comboboxentryAnne2;
  GtkWidget *labelCheckCinModif2;
  GtkWidget *comboboxentryMois2;
  GtkWidget *labelCheckAdresseModif;
  GtkWidget *labelCheckMailModif;
  GtkWidget *labelCheckTelModif;
  GtkWidget *labelCheckCinModif;
  GtkWidget *labelCheckPreomModif;
  GtkWidget *labelCheckNomModif;
  GtkWidget *labelCheckJourModif;
  GtkWidget *labelModifSucc;
  GtkWidget *comboboxentryJour2;
  GtkWidget *eventbox35;
  GtkWidget *Homme2;
  GSList *Homme2_group = NULL;
  GtkWidget *eventbox36;
  GtkWidget *Femme2;
  GtkWidget *buttonCherchModif;
  GtkWidget *alignment20;
  GtkWidget *hbox12;
  GtkWidget *image18;
  GtkWidget *label70;
  GtkWidget *buttonVmodif1;
  GtkWidget *alignment17;
  GtkWidget *hbox10;
  GtkWidget *image16;
  GtkWidget *label67;
  GtkWidget *buttonRModif;
  GtkWidget *alignment14;
  GtkWidget *hbox7;
  GtkWidget *image11;
  GtkWidget *label37;
  GtkWidget *TbuttonInitModif;
  GtkWidget *alignment30;
  GtkWidget *hbox19;
  GtkWidget *image27;
  GtkWidget *label79;
  GtkWidget *label81;
  GtkWidget *label30;
  GtkWidget *image31;
  GtkWidget *labelModif;
  GtkWidget *fixed4;
  GtkWidget *entryCinSupp;
  GtkWidget *buttonCherchSupp;
  GtkWidget *alignment21;
  GtkWidget *hbox13;
  GtkWidget *image19;
  GtkWidget *label71;
  GtkWidget *labelChekCinSupp;
  GtkWidget *buttonRSupp;
  GtkWidget *alignment15;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label38;
  GtkWidget *label31;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeviewsupp;
  GtkWidget *label82;
  GtkWidget *TbuttonAffichsupp;
  GtkWidget *alignment24;
  GtkWidget *hbox15;
  GtkWidget *image21;
  GtkWidget *label73;
  GtkWidget *label32;
  GtkWidget *image32;
  GtkWidget *label4;
  GtkWidget *alignment1;
  GtkWidget *fixed5;
  GtkWidget *entryCherchAffiche;
  GtkWidget *TbuttonAffichtous;
  GtkWidget *alignment23;
  GtkWidget *hbox14;
  GtkWidget *image20;
  GtkWidget *label72;
  GtkWidget *buttonRch;
  GtkWidget *alignment13;
  GtkWidget *hbox6;
  GtkWidget *image10;
  GtkWidget *label36;
  GtkWidget *buttonModif2;
  GtkWidget *alignment28;
  GtkWidget *hbox18;
  GtkWidget *image26;
  GtkWidget *label78;
  GtkWidget *scrolledwindow2;
  GtkWidget *GTK_TREE_VIEWChAffich;
  GtkWidget *label39;
  GtkWidget *buttonCherchAffiche;
  GtkWidget *image4;
  GtkWidget *label83;
  GtkWidget *label75;
  GtkWidget *image33;
  GtkWidget *labelCherch;

  Gestion_Des_Clients = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Gestion_Des_Clients, 959, 555);
  gtk_window_set_title (GTK_WINDOW (Gestion_Des_Clients), _("windowGestionDesClients"));

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_container_add (GTK_CONTAINER (Gestion_Des_Clients), eventbox4);

  alignment22 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (eventbox4), alignment22);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_container_add (GTK_CONTAINER (alignment22), eventbox3);

  notebookclient = gtk_notebook_new ();
  gtk_widget_show (notebookclient);
  gtk_container_add (GTK_CONTAINER (eventbox3), notebookclient);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (notebookclient), alignment5);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (alignment5), eventbox1);

  alignment8 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (eventbox1), alignment8);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_container_add (GTK_CONTAINER (alignment8), eventbox2);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (eventbox2), fixed1);
  gtk_widget_set_size_request (fixed1, 0, 0);

  entryNom = gtk_entry_new ();
  gtk_widget_show (entryNom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNom, 176, 64);
  gtk_widget_set_size_request (entryNom, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryNom), 19);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom), 8226);

  entryPrenom = gtk_entry_new ();
  gtk_widget_show (entryPrenom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPrenom, 176, 104);
  gtk_widget_set_size_request (entryPrenom, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryPrenom), 19);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrenom), 8226);

  entryTel = gtk_entry_new ();
  gtk_widget_show (entryTel);
  gtk_fixed_put (GTK_FIXED (fixed1), entryTel, 176, 184);
  gtk_widget_set_size_request (entryTel, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryTel), 15);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryTel), 8226);

  entryMail = gtk_entry_new ();
  gtk_widget_show (entryMail);
  gtk_fixed_put (GTK_FIXED (fixed1), entryMail, 176, 224);
  gtk_widget_set_size_request (entryMail, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryMail), 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMail), 8226);

  entryAdresse = gtk_entry_new ();
  gtk_widget_show (entryAdresse);
  gtk_fixed_put (GTK_FIXED (fixed1), entryAdresse, 176, 264);
  gtk_widget_set_size_request (entryAdresse, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryAdresse), 49);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAdresse), 8226);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox27, 240, 304);
  gtk_widget_set_size_request (eventbox27, 64, 29);

  comboboxentryMois = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryMois);
  gtk_container_add (GTK_CONTAINER (eventbox27), comboboxentryMois);
  gtk_widget_set_size_request (comboboxentryMois, 64, 29);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxentryMois), 13);
  GTK_WIDGET_SET_FLAGS (comboboxentryMois, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (comboboxentryMois, GTK_CAN_DEFAULT);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois), _("12"));

  labelCin = gtk_label_new (_("<span><b>CIN :</b></span>"));
  gtk_widget_show (labelCin);
  gtk_fixed_put (GTK_FIXED (fixed1), labelCin, 32, 144);
  gtk_widget_set_size_request (labelCin, 64, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelCin), TRUE);

  labelPrenom = gtk_label_new (_("<span><b>Pr\303\251nom :</b></span>"));
  gtk_widget_show (labelPrenom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelPrenom, 40, 104);
  gtk_widget_set_size_request (labelPrenom, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelPrenom), TRUE);

  labelTel = gtk_label_new (_("<span><b>N\302\260TEL :</b></span>"));
  gtk_widget_show (labelTel);
  gtk_fixed_put (GTK_FIXED (fixed1), labelTel, 32, 192);
  gtk_widget_set_size_request (labelTel, 80, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelTel), TRUE);

  labelMail = gtk_label_new (_("<span><b>E-mail :</b></span>"));
  gtk_widget_show (labelMail);
  gtk_fixed_put (GTK_FIXED (fixed1), labelMail, 32, 224);
  gtk_widget_set_size_request (labelMail, 81, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelMail), TRUE);

  labelAdresse = gtk_label_new (_("<span><b>Adresse  :</b></span>"));
  gtk_widget_show (labelAdresse);
  gtk_fixed_put (GTK_FIXED (fixed1), labelAdresse, 32, 264);
  gtk_widget_set_size_request (labelAdresse, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelAdresse), TRUE);

  label16 = gtk_label_new (_("<span><b>Naissance :</b></span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed1), label16, 32, 312);
  gtk_widget_set_size_request (label16, 104, 16);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  labelSex = gtk_label_new (_("<span><b>Sexe :</b></span>"));
  gtk_widget_show (labelSex);
  gtk_fixed_put (GTK_FIXED (fixed1), labelSex, 40, 344);
  gtk_widget_set_size_request (labelSex, 56, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelSex), TRUE);

  labelVerifJour = gtk_label_new ("");
  gtk_widget_show (labelVerifJour);
  gtk_fixed_put (GTK_FIXED (fixed1), labelVerifJour, 392, 304);
  gtk_widget_set_size_request (labelVerifJour, 344, 25);
  gtk_label_set_line_wrap (GTK_LABEL (labelVerifJour), TRUE);

  alignment26 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment26);
  gtk_fixed_put (GTK_FIXED (fixed1), alignment26, 176, 304);
  gtk_widget_set_size_request (alignment26, 63, 29);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_container_add (GTK_CONTAINER (alignment26), eventbox30);

  comboboxentryJour = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryJour);
  gtk_container_add (GTK_CONTAINER (eventbox30), comboboxentryJour);
  gtk_widget_set_size_request (comboboxentryJour, 63, 29);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxentryJour), 32);
  GTK_WIDGET_SET_FLAGS (comboboxentryJour, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (comboboxentryJour, GTK_CAN_DEFAULT);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour), _("31"));

  buttonVAjout = gtk_button_new ();
  gtk_widget_show (buttonVAjout);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonVAjout, 248, 400);
  gtk_widget_set_size_request (buttonVAjout, 112, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonVAjout), alignment2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label13 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Ajouter</span>"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox1), label13, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  buttonRAjout = gtk_button_new ();
  gtk_widget_show (buttonRAjout);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonRAjout, 488, 400);
  gtk_widget_set_size_request (buttonRAjout, 112, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonRAjout), alignment3);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Retour</span>"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox2), label14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox33, 176, 352);
  gtk_widget_set_size_request (eventbox33, 80, 16);

  Homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (Homme);
  gtk_container_add (GTK_CONTAINER (eventbox33), Homme);
  gtk_widget_set_size_request (Homme, 80, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Homme), Homme_group);
  Homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Homme));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (Homme), TRUE);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox34, 280, 352);
  gtk_widget_set_size_request (eventbox34, 80, 16);

  Femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (Femme);
  gtk_container_add (GTK_CONTAINER (eventbox34), Femme);
  gtk_widget_set_size_request (Femme, 80, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Femme), Homme_group);
  Homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Femme));

  calendarAjout = gtk_calendar_new ();
  gtk_widget_show (calendarAjout);
  gtk_fixed_put (GTK_FIXED (fixed1), calendarAjout, 608, 96);
  gtk_widget_set_size_request (calendarAjout, 176, 168);
  gtk_calendar_display_options (GTK_CALENDAR (calendarAjout),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  labelNom = gtk_label_new (_("<span><b>Nom :</b></span>"));
  gtk_widget_show (labelNom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelNom, 32, 64);
  gtk_widget_set_size_request (labelNom, 72, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelNom), TRUE);

  alignment29 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment29);
  gtk_fixed_put (GTK_FIXED (fixed1), alignment29, 176, 144);
  gtk_widget_set_size_request (alignment29, 160, 27);

  entryCin = gtk_entry_new ();
  gtk_widget_show (entryCin);
  gtk_container_add (GTK_CONTAINER (alignment29), entryCin);
  gtk_widget_set_size_request (entryCin, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryCin), 8);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCin), 8226);

  TbuttonInitAjout = gtk_button_new ();
  gtk_widget_show (TbuttonInitAjout);
  gtk_fixed_put (GTK_FIXED (fixed1), TbuttonInitAjout, 368, 400);
  gtk_widget_set_size_request (TbuttonInitAjout, 112, 37);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (TbuttonInitAjout), alignment27);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox17);

  image25 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox17), image25, FALSE, FALSE, 0);
  gtk_widget_set_size_request (image25, 20, -1);

  label76 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Initialiser</span>"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox17), label76, TRUE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label76), TRUE);

  comboboxentryAnne = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryAnne);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxentryAnne, 304, 304);
  gtk_widget_set_size_request (comboboxentryAnne, 80, 29);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxentryAnne), 95);
  GTK_WIDGET_SET_FLAGS (comboboxentryAnne, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (comboboxentryAnne, GTK_CAN_DEFAULT);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1910"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1911"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1912"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1913"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1914"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1915"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1916"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1917"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1918"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1919"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1920"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1921"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1922"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1923"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1924"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1925"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1926"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1927"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1928"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1929"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1930"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1931"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1932"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1933"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1934"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1935"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1936"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1937"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1938"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1939"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1940"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1941"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1942"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1943"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1944"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1945"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1946"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1947"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1948"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1949"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1950"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1951"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1952"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1953"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1954"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1955"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1956"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1957"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1958"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1959"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1960"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1961"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1962"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1963"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1964"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1965"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1966"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1967"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1968"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1969"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1970"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1971"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1972"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1973"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1974"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1975"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1976"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1977"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1978"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1979"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1980"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1981"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1982"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1983"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1984"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1985"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1986"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1987"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1988"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1989"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1990"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1991"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1992"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1993"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1994"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1995"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1996"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1997"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1998"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("1999 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("2000"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne), _("2004"));

  label80 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   MY FARM        </span>"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed1), label80, 0, 0);
  gtk_widget_set_size_request (label80, 192, 32);
  gtk_label_set_use_markup (GTK_LABEL (label80), TRUE);

  Tlabelcheckcalendar = gtk_label_new ("");
  gtk_widget_show (Tlabelcheckcalendar);
  gtk_fixed_put (GTK_FIXED (fixed1), Tlabelcheckcalendar, 576, 280);
  gtk_widget_set_size_request (Tlabelcheckcalendar, 312, 32);
  gtk_label_set_use_markup (GTK_LABEL (Tlabelcheckcalendar), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (Tlabelcheckcalendar), TRUE);

  label77 = gtk_label_new (_("<span><b>Date d'ajout de client  :</b></span>"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed1), label77, 592, 72);
  gtk_widget_set_size_request (label77, 184, 17);
  gtk_label_set_use_markup (GTK_LABEL (label77), TRUE);

  labelVerifAdresse = gtk_label_new ("");
  gtk_widget_show (labelVerifAdresse);
  gtk_fixed_put (GTK_FIXED (fixed1), labelVerifAdresse, 352, 264);
  gtk_widget_set_size_request (labelVerifAdresse, 232, 25);
  gtk_label_set_line_wrap (GTK_LABEL (labelVerifAdresse), TRUE);

  labelVerifMail = gtk_label_new ("");
  gtk_widget_show (labelVerifMail);
  gtk_fixed_put (GTK_FIXED (fixed1), labelVerifMail, 352, 224);
  gtk_widget_set_size_request (labelVerifMail, 264, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelVerifMail), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelVerifMail), TRUE);

  labelVerifTel = gtk_label_new ("");
  gtk_widget_show (labelVerifTel);
  gtk_fixed_put (GTK_FIXED (fixed1), labelVerifTel, 352, 184);
  gtk_widget_set_size_request (labelVerifTel, 296, 25);
  gtk_label_set_line_wrap (GTK_LABEL (labelVerifTel), TRUE);

  labelVerifCin = gtk_label_new (Q_("<span font_desc=\"black\"foreground=\"red\"> </span>"));
  gtk_widget_show (labelVerifCin);
  gtk_fixed_put (GTK_FIXED (fixed1), labelVerifCin, 352, 144);
  gtk_widget_set_size_request (labelVerifCin, 448, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelVerifCin), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelVerifCin), TRUE);
  gtk_label_set_single_line_mode (GTK_LABEL (labelVerifCin), TRUE);

  labelVerifPrenom = gtk_label_new ("");
  gtk_widget_show (labelVerifPrenom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelVerifPrenom, 352, 104);
  gtk_widget_set_size_request (labelVerifPrenom, 296, 25);
  gtk_label_set_line_wrap (GTK_LABEL (labelVerifPrenom), TRUE);

  labelVerifNom = gtk_label_new ("");
  gtk_widget_show (labelVerifNom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelVerifNom, 352, 64);
  gtk_widget_set_size_request (labelVerifNom, 288, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelVerifNom), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelVerifNom), TRUE);

  labelAjoutSucc = gtk_label_new ("");
  gtk_widget_show (labelAjoutSucc);
  gtk_fixed_put (GTK_FIXED (fixed1), labelAjoutSucc, 176, 24);
  gtk_widget_set_size_request (labelAjoutSucc, 232, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelAjoutSucc), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelAjoutSucc), TRUE);

  label28 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Ajouter Client</span>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed1), label28, 328, 0);
  gtk_widget_set_size_request (label28, 248, 25);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  image30 = create_pixmap (Gestion_Des_Clients, "xx.jpg");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed1), image30, 0, 0);
  gtk_widget_set_size_request (image30, 959, 531);
  gtk_widget_set_sensitive (image30, FALSE);

  labelAjout = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Ajouter</span>"));
  gtk_widget_show (labelAjout);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookclient), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookclient), 0), labelAjout);
  gtk_widget_set_sensitive (labelAjout, FALSE);
  gtk_label_set_use_markup (GTK_LABEL (labelAjout), TRUE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebookclient), fixed3);

  entryCinModif = gtk_entry_new ();
  gtk_widget_show (entryCinModif);
  gtk_fixed_put (GTK_FIXED (fixed3), entryCinModif, 328, 64);
  gtk_widget_set_size_request (entryCinModif, 168, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryCinModif), 8);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinModif), 8226);
  gtk_entry_set_activates_default (GTK_ENTRY (entryCinModif), TRUE);

  labelCinCherch = gtk_label_new (_("<span><b>Entrer la CIN du Client a Modifier :</b></span>"));
  gtk_widget_show (labelCinCherch);
  gtk_fixed_put (GTK_FIXED (fixed3), labelCinCherch, 16, 64);
  gtk_widget_set_size_request (labelCinCherch, 280, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelCinCherch), TRUE);

  entryNom2 = gtk_entry_new ();
  gtk_widget_show (entryNom2);
  gtk_fixed_put (GTK_FIXED (fixed3), entryNom2, 160, 136);
  gtk_widget_set_size_request (entryNom2, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryNom2), 19);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom2), 8226);

  entryPrenom2 = gtk_entry_new ();
  gtk_widget_show (entryPrenom2);
  gtk_fixed_put (GTK_FIXED (fixed3), entryPrenom2, 160, 176);
  gtk_widget_set_size_request (entryPrenom2, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryPrenom2), 19);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrenom2), 8226);

  entryCin2 = gtk_entry_new ();
  gtk_widget_show (entryCin2);
  gtk_fixed_put (GTK_FIXED (fixed3), entryCin2, 160, 216);
  gtk_widget_set_size_request (entryCin2, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryCin2), 14);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCin2), 8226);

  entryTel2 = gtk_entry_new ();
  gtk_widget_show (entryTel2);
  gtk_fixed_put (GTK_FIXED (fixed3), entryTel2, 160, 256);
  gtk_widget_set_size_request (entryTel2, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryTel2), 15);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryTel2), 8226);

  entryMail2 = gtk_entry_new ();
  gtk_widget_show (entryMail2);
  gtk_fixed_put (GTK_FIXED (fixed3), entryMail2, 160, 296);
  gtk_widget_set_size_request (entryMail2, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryMail2), 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMail2), 8226);

  entryAdresse2 = gtk_entry_new ();
  gtk_widget_show (entryAdresse2);
  gtk_fixed_put (GTK_FIXED (fixed3), entryAdresse2, 160, 336);
  gtk_widget_set_size_request (entryAdresse2, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entryAdresse2), 49);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAdresse2), 8226);

  label60 = gtk_label_new (_("<span><b>Sexe :</b></span>"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed3), label60, 48, 424);
  gtk_widget_set_size_request (label60, 57, 25);
  gtk_label_set_use_markup (GTK_LABEL (label60), TRUE);

  label59 = gtk_label_new (_("<span><b>Naissance :</b></span>"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed3), label59, 48, 384);
  gtk_widget_set_size_request (label59, 88, 17);
  gtk_label_set_use_markup (GTK_LABEL (label59), TRUE);

  label65 = gtk_label_new (_("<span><b>Adresse  :</b></span>"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed3), label65, 48, 336);
  gtk_widget_set_size_request (label65, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  label64 = gtk_label_new (_("<span><b>E-mail :</b></span>"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed3), label64, 32, 296);
  gtk_widget_set_size_request (label64, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (label64), TRUE);

  label57 = gtk_label_new (_("<span><b>N\302\260TEL :</b></span>"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed3), label57, 48, 256);
  gtk_widget_set_size_request (label57, 56, 25);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);

  label56 = gtk_label_new (_("<span><b>CIN :</b></span>"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed3), label56, 40, 200);
  gtk_widget_set_size_request (label56, 64, 56);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  label55 = gtk_label_new (_("<span><b>Pr\303\251nom :</b></span>"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed3), label55, 48, 176);
  gtk_widget_set_size_request (label55, 72, 25);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  label54 = gtk_label_new (_("<span><b>Nom :</b></span>"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed3), label54, 48, 136);
  gtk_widget_set_size_request (label54, 48, 24);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  eventbox29 = gtk_event_box_new ();
  gtk_widget_show (eventbox29);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox29, 288, 376);
  gtk_widget_set_size_request (eventbox29, 93, 29);

  comboboxentryAnne2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryAnne2);
  gtk_container_add (GTK_CONTAINER (eventbox29), comboboxentryAnne2);
  gtk_widget_set_size_request (comboboxentryAnne2, 93, 29);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxentryAnne2), 95);
  GTK_WIDGET_SET_FLAGS (comboboxentryAnne2, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (comboboxentryAnne2, GTK_CAN_DEFAULT);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1910"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1911"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1912"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1913"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1914"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1915"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1916"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1917"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1918"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1919"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1920"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1921"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1922"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1923"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1924"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1925"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1926"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1927"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1928"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1929"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1930"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1931"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1932"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1933"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1934"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1935"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1936"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1937"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1938"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1939"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1940"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1941"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1942"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1943"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1944"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1945"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1946"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1947"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1948"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1949"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1950"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1951"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1952"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1953"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1954"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1955"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1956"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1957"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1958"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1959"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1960"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1961"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1962"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1963"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1964"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1965"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1966"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1967"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1968"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1969"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1970"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1971"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1972"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1973"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1974"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1975"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1976"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1977"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1978"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1979"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1980"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1981"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1982"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1983"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1984"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1985"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1986"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1987"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1988"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1989"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1990"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1991"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1992"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1993"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1994"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1995"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1996"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1997"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1998"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("1999 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("2000"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryAnne2), _("2004"));

  labelCheckCinModif2 = gtk_label_new ("");
  gtk_widget_show (labelCheckCinModif2);
  gtk_fixed_put (GTK_FIXED (fixed3), labelCheckCinModif2, 328, 48);
  gtk_widget_set_size_request (labelCheckCinModif2, 136, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelCheckCinModif2), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelCheckCinModif2), TRUE);

  comboboxentryMois2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryMois2);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentryMois2, 224, 376);
  gtk_widget_set_size_request (comboboxentryMois2, 64, 29);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxentryMois2), 13);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryMois2), _("12"));

  labelCheckAdresseModif = gtk_label_new ("");
  gtk_widget_show (labelCheckAdresseModif);
  gtk_fixed_put (GTK_FIXED (fixed3), labelCheckAdresseModif, 336, 336);
  gtk_widget_set_size_request (labelCheckAdresseModif, 192, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelCheckAdresseModif), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelCheckAdresseModif), TRUE);

  labelCheckMailModif = gtk_label_new ("");
  gtk_widget_show (labelCheckMailModif);
  gtk_fixed_put (GTK_FIXED (fixed3), labelCheckMailModif, 336, 296);
  gtk_widget_set_size_request (labelCheckMailModif, 392, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelCheckMailModif), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelCheckMailModif), TRUE);

  labelCheckTelModif = gtk_label_new ("");
  gtk_widget_show (labelCheckTelModif);
  gtk_fixed_put (GTK_FIXED (fixed3), labelCheckTelModif, 336, 256);
  gtk_widget_set_size_request (labelCheckTelModif, 176, 23);
  gtk_label_set_use_markup (GTK_LABEL (labelCheckTelModif), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelCheckTelModif), TRUE);

  labelCheckCinModif = gtk_label_new ("");
  gtk_widget_show (labelCheckCinModif);
  gtk_fixed_put (GTK_FIXED (fixed3), labelCheckCinModif, 336, 216);
  gtk_widget_set_size_request (labelCheckCinModif, 376, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelCheckCinModif), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelCheckCinModif), TRUE);

  labelCheckPreomModif = gtk_label_new ("");
  gtk_widget_show (labelCheckPreomModif);
  gtk_fixed_put (GTK_FIXED (fixed3), labelCheckPreomModif, 336, 176);
  gtk_widget_set_size_request (labelCheckPreomModif, 200, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelCheckPreomModif), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelCheckPreomModif), TRUE);

  labelCheckNomModif = gtk_label_new ("");
  gtk_widget_show (labelCheckNomModif);
  gtk_fixed_put (GTK_FIXED (fixed3), labelCheckNomModif, 336, 136);
  gtk_widget_set_size_request (labelCheckNomModif, 200, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelCheckNomModif), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelCheckNomModif), TRUE);

  labelCheckJourModif = gtk_label_new ("");
  gtk_widget_show (labelCheckJourModif);
  gtk_fixed_put (GTK_FIXED (fixed3), labelCheckJourModif, 392, 376);
  gtk_widget_set_size_request (labelCheckJourModif, 216, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelCheckJourModif), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelCheckJourModif), TRUE);

  labelModifSucc = gtk_label_new ("");
  gtk_widget_show (labelModifSucc);
  gtk_fixed_put (GTK_FIXED (fixed3), labelModifSucc, 160, 104);
  gtk_widget_set_size_request (labelModifSucc, 200, 25);
  gtk_label_set_line_wrap (GTK_LABEL (labelModifSucc), TRUE);

  comboboxentryJour2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryJour2);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentryJour2, 160, 376);
  gtk_widget_set_size_request (comboboxentryJour2, 63, 29);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxentryJour2), 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryJour2), _("31"));

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox35, 160, 432);
  gtk_widget_set_size_request (eventbox35, 80, 16);

  Homme2 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme2"));
  gtk_widget_show (Homme2);
  gtk_container_add (GTK_CONTAINER (eventbox35), Homme2);
  gtk_widget_set_size_request (Homme2, 80, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Homme2), Homme2_group);
  Homme2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Homme2));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (Homme2), TRUE);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox36, 264, 432);
  gtk_widget_set_size_request (eventbox36, 80, 16);

  Femme2 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (Femme2);
  gtk_container_add (GTK_CONTAINER (eventbox36), Femme2);
  gtk_widget_set_size_request (Femme2, 80, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Femme2), Homme2_group);
  Homme2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Femme2));

  buttonCherchModif = gtk_button_new ();
  gtk_widget_show (buttonCherchModif);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonCherchModif, 496, 64);
  gtk_widget_set_size_request (buttonCherchModif, 120, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonCherchModif), alignment20);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox12);

  image18 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox12), image18, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("Selectionner"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox12), label70, FALSE, FALSE, 0);

  buttonVmodif1 = gtk_button_new ();
  gtk_widget_show (buttonVmodif1);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonVmodif1, 280, 464);
  gtk_widget_set_size_request (buttonVmodif1, 120, 37);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonVmodif1), alignment17);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox10);

  image16 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox10), image16, FALSE, FALSE, 0);

  label67 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Modifier</span>"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox10), label67, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label67), TRUE);

  buttonRModif = gtk_button_new ();
  gtk_widget_show (buttonRModif);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonRModif, 536, 464);
  gtk_widget_set_size_request (buttonRModif, 112, 37);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonRModif), alignment14);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox7);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox7), image11, FALSE, FALSE, 0);

  label37 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Retour</span>"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox7), label37, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  TbuttonInitModif = gtk_button_new ();
  gtk_widget_show (TbuttonInitModif);
  gtk_fixed_put (GTK_FIXED (fixed3), TbuttonInitModif, 408, 464);
  gtk_widget_set_size_request (TbuttonInitModif, 120, 37);
  gtk_button_set_focus_on_click (GTK_BUTTON (TbuttonInitModif), FALSE);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (TbuttonInitModif), alignment30);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox19);

  image27 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox19), image27, FALSE, FALSE, 0);

  label79 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Initialiser</span>"));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox19), label79, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label79), TRUE);

  label81 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   MY FARM        </span>"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed3), label81, 16, 0);
  gtk_widget_set_size_request (label81, 152, 32);
  gtk_label_set_use_markup (GTK_LABEL (label81), TRUE);

  label30 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Modification les informations d'un clients</span>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed3), label30, 288, 8);
  gtk_widget_set_size_request (label30, 360, 25);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  image31 = create_pixmap (Gestion_Des_Clients, "xx.jpg");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed3), image31, 0, 0);
  gtk_widget_set_size_request (image31, 959, 545);
  gtk_widget_set_sensitive (image31, FALSE);

  labelModif = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Modifier</span>"));
  gtk_widget_show (labelModif);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookclient), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookclient), 1), labelModif);
  gtk_label_set_use_markup (GTK_LABEL (labelModif), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebookclient), fixed4);

  entryCinSupp = gtk_entry_new ();
  gtk_widget_show (entryCinSupp);
  gtk_fixed_put (GTK_FIXED (fixed4), entryCinSupp, 328, 80);
  gtk_widget_set_size_request (entryCinSupp, 168, 30);
  gtk_entry_set_max_length (GTK_ENTRY (entryCinSupp), 8);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinSupp), 8226);

  buttonCherchSupp = gtk_button_new ();
  gtk_widget_show (buttonCherchSupp);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonCherchSupp, 496, 79);
  gtk_widget_set_size_request (buttonCherchSupp, 104, 31);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (buttonCherchSupp), alignment21);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox13);

  image19 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox13), image19, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox13), label71, FALSE, FALSE, 0);

  labelChekCinSupp = gtk_label_new ("");
  gtk_widget_show (labelChekCinSupp);
  gtk_fixed_put (GTK_FIXED (fixed4), labelChekCinSupp, 328, 56);
  gtk_widget_set_size_request (labelChekCinSupp, 208, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelChekCinSupp), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (labelChekCinSupp), TRUE);

  buttonRSupp = gtk_button_new ();
  gtk_widget_show (buttonRSupp);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonRSupp, 536, 408);
  gtk_widget_set_size_request (buttonRSupp, 120, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonRSupp), alignment15);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label38 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Retour</span>"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox8), label38, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label31 = gtk_label_new (_("<span><b>Entrer la CIN du Client a Supprimer :</b></span>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed4), label31, 40, 81);
  gtk_widget_set_size_request (label31, 280, 25);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 72, 120);
  gtk_widget_set_size_request (scrolledwindow1, 872, 272);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  treeviewsupp = gtk_tree_view_new ();
  gtk_widget_show (treeviewsupp);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeviewsupp);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeviewsupp), TRUE);

  label82 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   MY FARM        </span>"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed4), label82, 0, 0);
  gtk_widget_set_size_request (label82, 144, 40);
  gtk_label_set_use_markup (GTK_LABEL (label82), TRUE);

  TbuttonAffichsupp = gtk_button_new ();
  gtk_widget_show (TbuttonAffichsupp);
  gtk_fixed_put (GTK_FIXED (fixed4), TbuttonAffichsupp, 712, 72);
  gtk_widget_set_size_request (TbuttonAffichsupp, 136, 37);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (TbuttonAffichsupp), alignment24);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox15);

  image21 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox15), image21, FALSE, FALSE, 0);

  label73 = gtk_label_new (_("<span font_desc=\"black\"foreground=\"purple\"> Afficher Tous</span>"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox15), label73, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label73), TRUE);

  label32 = gtk_label_new_with_mnemonic (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Suppression d'un client</span>"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 288, 8);
  gtk_widget_set_size_request (label32, 360, 25);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  image32 = create_pixmap (Gestion_Des_Clients, "xx.jpg");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed4), image32, 0, 0);
  gtk_widget_set_size_request (image32, 959, 520);
  gtk_widget_set_sensitive (image32, FALSE);

  label4 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Supprimer</span>"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookclient), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookclient), 2), label4);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (notebookclient), alignment1);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (alignment1), fixed5);

  entryCherchAffiche = gtk_entry_new ();
  gtk_widget_show (entryCherchAffiche);
  gtk_fixed_put (GTK_FIXED (fixed5), entryCherchAffiche, 448, 80);
  gtk_widget_set_size_request (entryCherchAffiche, 168, 30);
  gtk_entry_set_max_length (GTK_ENTRY (entryCherchAffiche), 49);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCherchAffiche), 8226);

  TbuttonAffichtous = gtk_button_new ();
  gtk_widget_show (TbuttonAffichtous);
  gtk_fixed_put (GTK_FIXED (fixed5), TbuttonAffichtous, 712, 72);
  gtk_widget_set_size_request (TbuttonAffichtous, 136, 37);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (TbuttonAffichtous), alignment23);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox14);

  image20 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox14), image20, FALSE, FALSE, 0);

  label72 = gtk_label_new (_("<span font_desc=\"black\"foreground=\"purple\"> Afficher Tous</span>"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox14), label72, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label72), TRUE);

  buttonRch = gtk_button_new ();
  gtk_widget_show (buttonRch);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonRch, 536, 408);
  gtk_widget_set_size_request (buttonRch, 120, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonRch), alignment13);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox6);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox6), image10, FALSE, FALSE, 0);

  label36 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Retour</span>"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox6), label36, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  buttonModif2 = gtk_button_new ();
  gtk_widget_show (buttonModif2);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonModif2, 360, 408);
  gtk_widget_set_size_request (buttonModif2, 128, 37);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (buttonModif2), alignment28);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox18);

  image26 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox18), image26, FALSE, FALSE, 0);

  label78 = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Modifier</span>"));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox18), label78, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label78), TRUE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow2, 72, 120);
  gtk_widget_set_size_request (scrolledwindow2, 872, 272);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  GTK_TREE_VIEWChAffich = gtk_tree_view_new ();
  gtk_widget_show (GTK_TREE_VIEWChAffich);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), GTK_TREE_VIEWChAffich);
  gtk_widget_set_size_request (GTK_TREE_VIEWChAffich, 928, 280);
  GTK_WIDGET_SET_FLAGS (GTK_TREE_VIEWChAffich, GTK_CAN_DEFAULT);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (GTK_TREE_VIEWChAffich), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (GTK_TREE_VIEWChAffich), TRUE);

  label39 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> chercher  des clients</span>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed5), label39, 232, 8);
  gtk_widget_set_size_request (label39, 360, 25);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  buttonCherchAffiche = gtk_button_new ();
  gtk_widget_show (buttonCherchAffiche);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonCherchAffiche, 624, 80);
  gtk_widget_set_size_request (buttonCherchAffiche, 32, 30);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (buttonCherchAffiche), image4);

  label83 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   MY FARM        </span>"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed5), label83, 8, 1);
  gtk_widget_set_size_request (label83, 144, 39);
  gtk_label_set_use_markup (GTK_LABEL (label83), TRUE);

  label75 = gtk_label_new (_("<span><b>Chercher :</b></span>"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed5), label75, 304, 80);
  gtk_widget_set_size_request (label75, 176, 26);
  gtk_label_set_use_markup (GTK_LABEL (label75), TRUE);

  image33 = create_pixmap (Gestion_Des_Clients, "xx.jpg");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed5), image33, 0, 0);
  gtk_widget_set_size_request (image33, 954, 521);
  gtk_widget_set_sensitive (image33, FALSE);

  labelCherch = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> Chercher</span>"));
  gtk_widget_show (labelCherch);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookclient), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookclient), 3), labelCherch);
  gtk_label_set_use_markup (GTK_LABEL (labelCherch), TRUE);

  g_signal_connect ((gpointer) entryMail, "changed",
                    G_CALLBACK (on_entryMail_changed),
                    NULL);
  g_signal_connect ((gpointer) comboboxentryJour, "button_press_event",
                    G_CALLBACK (on_comboboxentryJour_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) buttonVAjout, "clicked",
                    G_CALLBACK (on_buttonVAjout_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRAjout, "clicked",
                    G_CALLBACK (on_buttonRAjout_clicked),
                    NULL);
  g_signal_connect ((gpointer) Homme, "toggled",
                    G_CALLBACK (on_Homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) calendarAjout, "day_selected",
                    G_CALLBACK (on_calendarAjout_day_selected),
                    NULL);
  g_signal_connect ((gpointer) entryCin, "changed",
                    G_CALLBACK (on_entryCin_changed),
                    NULL);
  g_signal_connect ((gpointer) TbuttonInitAjout, "clicked",
                    G_CALLBACK (on_TbuttonInitAjout_clicked),
                    NULL);
  g_signal_connect ((gpointer) comboboxentryJour2, "button_press_event",
                    G_CALLBACK (on_comboboxentryJour_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) Homme2, "toggled",
                    G_CALLBACK (on_Homme2_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonCherchModif, "clicked",
                    G_CALLBACK (on_buttonCherchModif_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonVmodif1, "clicked",
                    G_CALLBACK (on_buttonVmodif1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRModif, "clicked",
                    G_CALLBACK (on_buttonRModif_clicked),
                    NULL);
  g_signal_connect ((gpointer) TbuttonInitModif, "clicked",
                    G_CALLBACK (on_TbuttonInitModif_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonCherchSupp, "clicked",
                    G_CALLBACK (on_buttonCherchSupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRSupp, "clicked",
                    G_CALLBACK (on_buttonRSupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewsupp, "row_activated",
                    G_CALLBACK (on_treeviewsupp_row_activated),
                    NULL);
  g_signal_connect ((gpointer) TbuttonAffichsupp, "clicked",
                    G_CALLBACK (on_TbuttonAffichsupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) TbuttonAffichtous, "clicked",
                    G_CALLBACK (on_TbuttonAffichtous_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRch, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModif2, "clicked",
                    G_CALLBACK (on_buttonModif2_clicked),
                    NULL);
  g_signal_connect ((gpointer) GTK_TREE_VIEWChAffich, "row_activated",
                    G_CALLBACK (on_GTK_TREE_VIEWChAffich_row_activated),
                    NULL);
  g_signal_connect ((gpointer) GTK_TREE_VIEWChAffich, "drag_end",
                    G_CALLBACK (on_GTK_TREE_VIEWChAffich_drag_end),
                    NULL);
  g_signal_connect ((gpointer) GTK_TREE_VIEWChAffich, "select_all",
                    G_CALLBACK (on_GTK_TREE_VIEWChAffich_select_all),
                    NULL);
  g_signal_connect ((gpointer) buttonCherchAffiche, "clicked",
                    G_CALLBACK (on_buttonCherchAffiche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_Des_Clients, Gestion_Des_Clients, "Gestion_Des_Clients");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, notebookclient, "notebookclient");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryNom, "entryNom");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryPrenom, "entryPrenom");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryTel, "entryTel");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryMail, "entryMail");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryAdresse, "entryAdresse");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, comboboxentryMois, "comboboxentryMois");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCin, "labelCin");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelPrenom, "labelPrenom");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelTel, "labelTel");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelMail, "labelMail");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelAdresse, "labelAdresse");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label16, "label16");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelSex, "labelSex");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelVerifJour, "labelVerifJour");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, comboboxentryJour, "comboboxentryJour");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, buttonVAjout, "buttonVAjout");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image1, "image1");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label13, "label13");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, buttonRAjout, "buttonRAjout");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image2, "image2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label14, "label14");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, Homme, "Homme");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, Femme, "Femme");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, calendarAjout, "calendarAjout");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelNom, "labelNom");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryCin, "entryCin");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, TbuttonInitAjout, "TbuttonInitAjout");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image25, "image25");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label76, "label76");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, comboboxentryAnne, "comboboxentryAnne");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label80, "label80");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, Tlabelcheckcalendar, "Tlabelcheckcalendar");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label77, "label77");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelVerifAdresse, "labelVerifAdresse");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelVerifMail, "labelVerifMail");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelVerifTel, "labelVerifTel");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelVerifCin, "labelVerifCin");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelVerifPrenom, "labelVerifPrenom");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelVerifNom, "labelVerifNom");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelAjoutSucc, "labelAjoutSucc");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label28, "label28");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image30, "image30");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelAjout, "labelAjout");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryCinModif, "entryCinModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCinCherch, "labelCinCherch");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryNom2, "entryNom2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryPrenom2, "entryPrenom2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryCin2, "entryCin2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryTel2, "entryTel2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryMail2, "entryMail2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryAdresse2, "entryAdresse2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label60, "label60");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label59, "label59");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label65, "label65");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label64, "label64");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label57, "label57");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label56, "label56");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label55, "label55");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label54, "label54");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, comboboxentryAnne2, "comboboxentryAnne2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCheckCinModif2, "labelCheckCinModif2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, comboboxentryMois2, "comboboxentryMois2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCheckAdresseModif, "labelCheckAdresseModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCheckMailModif, "labelCheckMailModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCheckTelModif, "labelCheckTelModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCheckCinModif, "labelCheckCinModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCheckPreomModif, "labelCheckPreomModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCheckNomModif, "labelCheckNomModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCheckJourModif, "labelCheckJourModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelModifSucc, "labelModifSucc");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, comboboxentryJour2, "comboboxentryJour2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, Homme2, "Homme2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, Femme2, "Femme2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, buttonCherchModif, "buttonCherchModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image18, "image18");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label70, "label70");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, buttonVmodif1, "buttonVmodif1");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image16, "image16");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label67, "label67");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, buttonRModif, "buttonRModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image11, "image11");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label37, "label37");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, TbuttonInitModif, "TbuttonInitModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image27, "image27");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label79, "label79");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label81, "label81");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label30, "label30");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image31, "image31");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelModif, "labelModif");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryCinSupp, "entryCinSupp");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, buttonCherchSupp, "buttonCherchSupp");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image19, "image19");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label71, "label71");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelChekCinSupp, "labelChekCinSupp");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, buttonRSupp, "buttonRSupp");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image12, "image12");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label38, "label38");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label31, "label31");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, treeviewsupp, "treeviewsupp");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label82, "label82");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, TbuttonAffichsupp, "TbuttonAffichsupp");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image21, "image21");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label73, "label73");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label32, "label32");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image32, "image32");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label4, "label4");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, entryCherchAffiche, "entryCherchAffiche");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, TbuttonAffichtous, "TbuttonAffichtous");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image20, "image20");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label72, "label72");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, buttonRch, "buttonRch");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image10, "image10");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label36, "label36");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, buttonModif2, "buttonModif2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image26, "image26");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label78, "label78");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, GTK_TREE_VIEWChAffich, "GTK_TREE_VIEWChAffich");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label39, "label39");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, buttonCherchAffiche, "buttonCherchAffiche");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image4, "image4");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label83, "label83");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, label75, "label75");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, image33, "image33");
  GLADE_HOOKUP_OBJECT (Gestion_Des_Clients, labelCherch, "labelCherch");

  gtk_widget_grab_focus (comboboxentryAnne2);
  gtk_widget_grab_default (comboboxentryMois);
  return Gestion_Des_Clients;
}

GtkWidget*
create_Principal2 (void)
{
  GtkWidget *Principal2;
  GtkWidget *fixed6;
  GtkWidget *image28;
  GtkWidget *label40;
  GtkWidget *buttonGestionClients;
  GtkWidget *anplussech1;
  GtkWidget *label84;
  GtkWidget *image29;

  Principal2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Principal2, 959, 520);
  gtk_window_set_title (GTK_WINDOW (Principal2), _("windowPrincipal2"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Principal2), fixed6);

  image28 = create_pixmap (Principal2, "xx.jpg");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed6), image28, 0, 552);
  gtk_widget_set_size_request (image28, 792, 512);
  gtk_widget_set_sensitive (image28, FALSE);

  label40 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'>Bienvenue dans votre espace clients</span>"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed6), label40, 280, 32);
  gtk_widget_set_size_request (label40, 392, 25);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  buttonGestionClients = gtk_button_new_with_mnemonic (_("Gestion Des Clients"));
  gtk_widget_show (buttonGestionClients);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonGestionClients, 360, 136);
  gtk_widget_set_size_request (buttonGestionClients, 256, 56);

  anplussech1 = gtk_button_new_with_mnemonic (_("L'ann\303\251 la plus s\303\251che"));
  gtk_widget_show (anplussech1);
  gtk_fixed_put (GTK_FIXED (fixed6), anplussech1, 360, 248);
  gtk_widget_set_size_request (anplussech1, 256, 56);

  label84 = gtk_label_new (_("<span  foreground='#7bB4b1'  size='x-large' weight='bold'  style='ROMAN'      >   MY FARM        </span>"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed6), label84, 8, 32);
  gtk_widget_set_size_request (label84, 128, 40);
  gtk_label_set_use_markup (GTK_LABEL (label84), TRUE);

  image29 = create_pixmap (Principal2, "xx.jpg");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed6), image29, 0, 0);
  gtk_widget_set_size_request (image29, 959, 520);
  gtk_widget_set_sensitive (image29, FALSE);

  g_signal_connect ((gpointer) buttonGestionClients, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) anplussech1, "clicked",
                    G_CALLBACK (on_anplussech1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Principal2, Principal2, "Principal2");
  GLADE_HOOKUP_OBJECT (Principal2, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Principal2, image28, "image28");
  GLADE_HOOKUP_OBJECT (Principal2, label40, "label40");
  GLADE_HOOKUP_OBJECT (Principal2, buttonGestionClients, "buttonGestionClients");
  GLADE_HOOKUP_OBJECT (Principal2, anplussech1, "anplussech1");
  GLADE_HOOKUP_OBJECT (Principal2, label84, "label84");
  GLADE_HOOKUP_OBJECT (Principal2, image29, "image29");

  return Principal2;
}

GtkWidget*
create_AnSech (void)
{
  GtkWidget *AnSech;
  GtkWidget *fixed8;
  GtkWidget *label88;
  GtkWidget *TbuttonAfficheAnSech;
  GtkWidget *alignment31;
  GtkWidget *hbox20;
  GtkWidget *image35;
  GtkWidget *label87;
  GtkWidget *labelAnSech;
  GtkWidget *textviewAnseche;
  GtkWidget *buttonRetourAn;
  GtkWidget *alignment32;
  GtkWidget *hbox21;
  GtkWidget *image37;
  GtkWidget *label89;
  GtkWidget *image36;

  AnSech = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (AnSech, 954, 520);
  gtk_window_set_title (GTK_WINDOW (AnSech), _("window1"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (AnSech), fixed8);

  label88 = gtk_label_new (_("<span  foreground='#7bB4b1'  size='x-large' weight='bold'  style='ROMAN'      >   MY FARM        </span>"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed8), label88, 0, 0);
  gtk_widget_set_size_request (label88, 128, 32);
  gtk_label_set_use_markup (GTK_LABEL (label88), TRUE);

  TbuttonAfficheAnSech = gtk_button_new ();
  gtk_widget_show (TbuttonAfficheAnSech);
  gtk_fixed_put (GTK_FIXED (fixed8), TbuttonAfficheAnSech, 320, 272);
  gtk_widget_set_size_request (TbuttonAfficheAnSech, 224, 32);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (TbuttonAfficheAnSech), alignment31);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox20);

  image35 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox20), image35, FALSE, FALSE, 0);

  label87 = gtk_label_new (_("<span font_desc=\"black\"foreground=\"green\"> Afficher l'anne </span>"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox20), label87, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label87), TRUE);

  labelAnSech = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> L'ann\303\251e La Plus S\303\251che : </span>"));
  gtk_widget_show (labelAnSech);
  gtk_fixed_put (GTK_FIXED (fixed8), labelAnSech, 288, 168);
  gtk_widget_set_size_request (labelAnSech, 216, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelAnSech), TRUE);

  textviewAnseche = gtk_label_new ("");
  gtk_widget_show (textviewAnseche);
  gtk_fixed_put (GTK_FIXED (fixed8), textviewAnseche, 504, 168);
  gtk_widget_set_size_request (textviewAnseche, 80, 24);

  buttonRetourAn = gtk_button_new ();
  gtk_widget_show (buttonRetourAn);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonRetourAn, 584, 272);
  gtk_widget_set_size_request (buttonRetourAn, 96, 29);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (buttonRetourAn), alignment32);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox21);

  image37 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox21), image37, FALSE, FALSE, 0);

  label89 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label89);
  gtk_box_pack_start (GTK_BOX (hbox21), label89, FALSE, FALSE, 0);

  image36 = create_pixmap (AnSech, "xx.jpg");
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed8), image36, 0, 0);
  gtk_widget_set_size_request (image36, 957, 520);
  gtk_widget_set_sensitive (image36, FALSE);

  g_signal_connect ((gpointer) TbuttonAfficheAnSech, "clicked",
                    G_CALLBACK (on_TbuttonAfficheAnSech_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRetourAn, "clicked",
                    G_CALLBACK (on_buttonRetourAn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AnSech, AnSech, "AnSech");
  GLADE_HOOKUP_OBJECT (AnSech, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (AnSech, label88, "label88");
  GLADE_HOOKUP_OBJECT (AnSech, TbuttonAfficheAnSech, "TbuttonAfficheAnSech");
  GLADE_HOOKUP_OBJECT (AnSech, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (AnSech, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (AnSech, image35, "image35");
  GLADE_HOOKUP_OBJECT (AnSech, label87, "label87");
  GLADE_HOOKUP_OBJECT (AnSech, labelAnSech, "labelAnSech");
  GLADE_HOOKUP_OBJECT (AnSech, textviewAnseche, "textviewAnseche");
  GLADE_HOOKUP_OBJECT (AnSech, buttonRetourAn, "buttonRetourAn");
  GLADE_HOOKUP_OBJECT (AnSech, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (AnSech, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (AnSech, image37, "image37");
  GLADE_HOOKUP_OBJECT (AnSech, label89, "label89");
  GLADE_HOOKUP_OBJECT (AnSech, image36, "image36");

  return AnSech;
}

