/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  char cin45[15];
  GtkWidget *Gestion_Des_Clients;
  GtkWidget *Principal2;
  GtkWidget *AnSech;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
  
  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*Gestion_Des_Clients = create_Gestion_Des_Clients ();
  gtk_widget_show (Gestion_Des_Clients);*/
  Principal2 = create_Principal2 ();
  gtk_widget_show (Principal2);
  /*AnSech = create_AnSech ();
  gtk_widget_show (AnSech);*/

  gtk_main ();
  return 0;
}

